# Needs pre-commit installed both to system and to local repo to do anything
# See https://pre-commit.com/

repos:
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.4.0
    hooks:
      - id: go-fmt
      - id: go-imports
      - id: go-build
      - id: go-mod-tidy
